[project]
name = "temporal_fusion_transformer"
version = "0.0.1dev1"
description = "TF2 re-write of Temporal Fusion Transformer model."
readme = "Readme.md"
requires-python = ">=3.8"
authors = [
    { name = "Artem Sereda", email = "artem.sereda.tub@gmail.com" },
]
maintainers = [
    { name = "Artem Sereda", email = "artem.sereda.tub@gmail.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "flax==0.7.1",
    "jax==0.4.14",
    "jaxlib==0.4.14",
    "jaxtyping==0.2.20",
    "ml-collections==0.1.1"
]
[project.optional-dependencies]
training = [
    "absl_extra",
    "clu==0.0.9",
    "optax==0.1.7",
    "tensorflow==2.13.0; sys_platform == 'linux'",
    "tensorflow_macos==2.13.0; sys_platform == 'darwin'",
]
datasets = [
    "tensorflow==2.13.0; sys_platform == 'linux'",
    "tensorflow_macos==2.13.0; sys_platform == 'darwin'",
    "toolz==0.12.0",
    "polars==0.18.5",
    "pyarrow>=12.0.1",
    "py7zr",
    "tqdm",
    "kaggle",
]
tests = [
    "pytest",
    "chex"
]
dev = [
    "temporal_fusion_transformer[tests,datasets,training]",
    "black",
]
[project.urls]
"Homepage" = "https://github.com/aaarrti/temporal_fusion_transformer"


[build-system]
requires = ["flit-core >= 3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 120