[project]
name = "temporal_fusion_transformer"
version = "0.0.1dev1"
description = "TF2 re-write of Temporal Fusion Transformer model."
readme = "Readme.md"
requires-python = ">=3.8"
authors = [
    { name = "Artem Sereda", email = "artem.sereda.tub@gmail.com" },
]
maintainers = [
    { name = "Artem Sereda", email = "artem.sereda.tub@gmail.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "flax==0.7.2",
    "jax[cpu]==0.4.14;sys_platform=='darwin'",
    "jaxlib==0.4.14",
    "jaxtyping==0.2.20",
]
[project.optional-dependencies]
tensorflow = [
    "tensorflow>=2.12.0<2.13.0; sys_platform == 'linux'",
    "tensorflow_macos>=2.12.0<2.13.0; sys_platform == 'darwin'",
]
training = [
    "absl-py==1.4.0",
    "ml-collections==0.1.1",
    "clu==0.0.9",
    "msgpack==1.0.5",
    "optax==0.1.7",
    "orbax_checkpoint==0.3.5",
    # No pinned version for my package, since I always want the lastest
    "absl_extra",
    "temporal_fusion_transformer[tensorflow]"
]
datasets = [
    "toolz==0.12.0",
    "polars==0.18.15",
    "pyarrow>=12.0.1",
    "py7zr==0.20.5",
    "tqdm==4.65.0",
    "kaggle==1.5.16",
    "ordered_set==4.1.0",
    "temporal_fusion_transformer[tensorflow]"
]
tests = [
    "pytest==7.4.0",
    "chex==0.1.7"
]
dev = [
    "temporal_fusion_transformer[tests,datasets,training]",
    "black[jupyter]==23.7.0",
    "isort==5.12.0",
    "jupyter==1.0.0"
]
[project.urls]
"Homepage" = "https://github.com/aaarrti/temporal_fusion_transformer"


[build-system]
requires = ["flit-core >= 3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 120