[project]
name = "temporal_fusion_transformer"
version = "0.0.1dev1"
description = "JAX re-write of Temporal Fusion Transformer"
readme = "Readme.md"
requires-python = ">=3.8"
authors = [
    { name = "Artem Sereda", email = "artem.sereda.tub@gmail.com" },
]
maintainers = [
    { name = "Artem Sereda", email = "artem.sereda.tub@gmail.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
]
dependencies = [
    "flax==0.7.4",
    "jax==0.4.13;sys_platform=='darwin'",
    "jax[cpu]==0.4.13;sys_platform=='darwin'",
    "jaxlib==0.4.13",
    "jaxtyping==0.2.21",
    "numpy==1.24.3"
]
[project.optional-dependencies]
tensorflow = [
    "tensorflow==2.13.0; sys_platform == 'linux'",
    "tensorflow_macos==2.13.0; sys_platform == 'darwin'",
]
training = [
    "absl-py==1.4.0",
    "ml-collections==0.1.1",
    "clu==0.0.9",
    "msgpack==1.0.5",
    "optax==0.1.7",
    "orbax_checkpoint==0.3.5",
    # No pinned version for my package, since I always want the lastest
    "absl_extra",
    "temporal_fusion_transformer[tensorflow]"
]
datasets = [
    "toolz==0.12.0",
    "polars==0.18.15",
    "tqdm==4.66.1",
    "temporal_fusion_transformer[tensorflow]"
]
tests = [
    "pytest",
    "chex==0.1.7"
]
dev = [
    "temporal_fusion_transformer[tests,datasets,training]",
    "black[jupyter]",
    "isort",
    "jupyter",
    "ruff"
]
[project.urls]
"Homepage" = "https://github.com/aaarrti/temporal_fusion_transformer"


[build-system]
requires = ["flit-core >= 3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120