[tox]
requires =
    tox>=4.2
    virtualenv>20.2
env_list =
    py{310, 39, 38}
skip_missing_interpreters = true
skip_sdist = true

[testenv]
deps =
    .[test]
commands =
    python3 -m pytest -s -v {posargs}
pass_env =
    TF_XLA_FLAGS

[testenv:coverage]
commands =
    python3 -m pytest --cov-report term --cov-report html:htmlcov --cov-report xml --cov=temporal_fusion_transformer

[gh]
python =
    3.8 = py38
    3.9 = py39
    3.10 = py310