total_time_steps = 120
encoder_steps = 90
num_outputs = 1
known_categories_sizes = [
    12, # month
    31, # day of month
    7, # day of week
    39, # national holiday
    2, # regional hol
    6, # local holiday
    2, # on promotion
    2, # open
]
static_categories_sizes = [
    3586, # item nbr
    53, # store nbr
    22, # city
    16, # state,
    5, # type
    17, # cluster
    32, # family
    317, # class
    2, # perishable
]
input_known_real_idx = []
input_observed_idx = [
    0, # oil price
    1, # transactions
]
input_static_idx = [
    2, # item nbr
    3, # store nbr
    4, # city
    5, # state,
    6, # type
    7, # cluster
    8, # family
    9, # class
]
input_known_categorical_idx = [
    10, # month
    11, # day of month
    12, # day of week
    13, # national holiday
    14, # regional hol
    15, # local holiday
    16, # on promotion
    17, # open
]
validation_boundary=2015-12-01
num_attention_heads=12
num_decoder_blocks=1
hidden_layer_size=64
dropout_rate=0.1
unroll=false
learning_rate=1e-3
decay_steps=0
decay_alpha=0
clipnorm=0
use_ema=false
weight_decay=0
batch_size=256
compression='GZIP'
drop_remainder=true
shuffle_buffer_size=1024
quantiles = [0.1, 0.5, 0.9]
epochs=1
test_split_save_format='parquet'
test_boundary={}
split_overlap={}






