name: Lint

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: python -m pip install .[dev]

      - name: Lint with ruff
        run: hatch fmt --check src/

      - name: Lint with mypy
        run: mypy src/