name: Lint

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.10", 3.11", 3.12" ]

    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: ${{ matrix.python-version }}

      - name: Install hatch
        run: python -m pip install hatch

      - name: Lint with ruff
        run: hatch fmt --check src/

      - name: Lint with mypy
        run: mypy src/

      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          jupyter: true